---
classes:
  - sysctl
  - ntp
  - firewall
  - timezone

sysctl:
  fs.suid_dumpable: 1
  net.ipv4.tcp_timestamps: 1
  net.ipv4.tcp_tw_reuse: 1
  net.ipv4.tcp_sack: 0

timezone::timezone: 'Europe/Moscow'
